inherit_from: .rubocop_todo.yml

require: rubocop-rspec
AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4

Metrics/BlockLength:
  Exclude:
    - spec/*.rb
